# Generated by Django 4.2.3 on 2023-07-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0002_resume_institute_resume_qualification"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="skills",
            field=models.CharField(default="", max_length=300),
        ),
    ]
